const fs = require('fs')
let content = fs.readFileSync('lib/i18n/zh.ts', 'utf8')
content = content.replace("dashboard: '工单概览'", "dashboard: '概览'")
fs.writeFileSync('lib/i18n/zh.ts', content)
console.log('done')
