const fs = require('fs')
const existing = fs.readFileSync('app/jobs/new/page.tsx', 'utf8')
const fixed = "'use client'\n" + existing.replace(/^'use client'\n?/, '')
fs.writeFileSync('app/jobs/new/page.tsx', fixed)
console.log('First 3 chars:', JSON.stringify(fixed.slice(0, 20)))
