'use client'

import { useEffect, useState } from 'react'
import { createClient } from '../../../utils/supabase/client'
import Link from 'next/link'
import { useLanguage } from '../../../lib/i18n/LanguageContext'

function getQuarter(date: Date) {
  const month = date.getMonth()
  if (month <= 2) return 1
  if (month <= 5) return 2
  if (month <= 8) return 3
  return 4
}

function getQuarterRange(year: number, quarter: number) {
  const starts = [0, 3, 6, 9]
  const start = new Date(year, starts[quarter - 1], 1)
  const end = new Date(year, starts[quarter - 1] + 3, 0)
  return { start, end }
}

export default function BASReport() {
  const supabase = createClient()
  const { lang } = useLanguage()
  const [entries, setEntries] = useState<any[]>([])
  const today = new Date()
  const [selectedYear, setSelectedYear] = useState(today.getFullYear())
  const [selectedQuarter, setSelectedQuarter] = useState(getQuarter(today))
  const [copied, setCopied] = useState(false)
  const [taxPct, setTaxPct] = useState(30)
  const [mounted, setMounted] = useState(false)
  useEffect(() => setMounted(true), [])

  useEffect(() => {
    supabase.from('job_entries').select('*').then(({ data }: { data: any }) => setEntries(data || []))
  }, [])

  const { start, end } = getQuarterRange(selectedYear, selectedQuarter)

  const periodEntries = entries.filter(e => {
    const d = new Date(e.entry_date || e.created_at)
    return d >= start && d <= end
  })

  const invoiceEntries = periodEntries.filter(e => e.type === 'invoice')
  const costEntries = periodEntries.filter(e => ['material', 'subcontract', 'fuel'].includes(e.type))
  const laborEntries = periodEntries.filter(e => e.type === 'labor')

  const grossOf = (e:any) => {
    const amt = e.type === 'labor' ? Number(e.hours)*Number(e.hourly_rate) : Number(e.amount)
    return e.gst_status === 'exclusive' ? (amt||0)*1.1 : (amt||0)
  }
  const totalSales = invoiceEntries.reduce((sum, e) => sum + grossOf(e), 0)
  const totalCosts = costEntries.reduce((sum, e) => sum + grossOf(e), 0)
  const totalLabor = laborEntries.reduce((sum, e) => sum + Number(e.hours) * Number(e.hourly_rate), 0)
  const totalExpenses = totalCosts + totalLabor

  const gstOf = (e:any) => {
    const amt = e.type === 'labor' ? Number(e.hours)*Number(e.hourly_rate) : Number(e.amount)
    if (e.gst_status === 'inclusive') return (amt||0)/11
    if (e.gst_status === 'exclusive') return (amt||0)*0.1
    return 0
  }
  const gstCollected = invoiceEntries.reduce((sum,e)=>sum+gstOf(e),0)
  const gstPaid = [...costEntries].reduce((sum,e)=>sum+gstOf(e),0)  // labor(人工)不参与GST credit:工资非taxable supply
  const netGST = gstCollected - gstPaid

  const salesExGST = totalSales - gstCollected
  const costsExGST = totalCosts - gstPaid

  const MON = ['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec']
  const fmtD = (d:Date) => d.getDate() + ' ' + MON[d.getMonth()]
  const basDue = end.getMonth() === 11 ? new Date(end.getFullYear()+1, 1, 28) : new Date(end.getFullYear(), end.getMonth()+1, 28)
  const dueStr = fmtD(basDue) + ' ' + basDue.getFullYear()
  const dueDays = Math.ceil((basDue.getTime() - Date.now()) / 86400000)
  const quarterLabel = 'Q' + selectedQuarter + ' ' + selectedYear + ' (' + fmtD(start) + ' – ' + fmtD(end) + ' ' + end.getFullYear() + ')'

  const basText = `BAS REPORT (Simpler BAS) — ${quarterLabel}
━━━━━━━━━━━━━━━━━━━━━━━━
G1  Total Sales (inc GST):     $${totalSales.toFixed(2)}
━━━━━━━━━━━━━━━━━━━━━━━━
1A  GST on Sales:               $${gstCollected.toFixed(2)}
1B  GST on Purchases:           $${gstPaid.toFixed(2)}
━━━━━━━━━━━━━━━━━━━━━━━━
NET GST PAYABLE (1A - 1B):     $${netGST.toFixed(2)}
━━━━━━━━━━━━━━━━━━━━━━━━
Simpler BAS: most AU small businesses report only G1, 1A, 1B.
Generated by CIMO`

  async function copyToClipboard() {
    await navigator.clipboard.writeText(basText)
    setCopied(true)
    setTimeout(() => setCopied(false), 2000)
  }

  const years = [today.getFullYear() - 1, today.getFullYear()]

  return (
    <div className="min-h-screen bg-gray-50 dark:bg-gray-950">
      <nav className="bg-white dark:bg-gray-900 border-b border-gray-200 dark:border-gray-700/60 px-6 py-4">
        <div className="max-w-2xl mx-auto flex items-center gap-3">
          <Link href="/tax" className="text-gray-500 dark:text-[#8E8E93] text-sm">← {lang === 'zh' ? '税务中心' : 'Tax Hub'}</Link>
          <h1 className="font-semibold text-gray-900 dark:text-white">BAS Report</h1>
        </div>
      </nav>

      <main className="max-w-2xl mx-auto px-4 py-6 space-y-4">
        <div className="bg-amber-50 dark:bg-[#3A2E00]/40 border border-amber-200 dark:border-[#5C4A00] rounded-2xl px-4 py-3">
          <p className="text-xs text-amber-800 dark:text-[#E3B341] leading-relaxed">⚠️ {lang === 'zh'
            ? 'CIMO 是记账与计算工具，不是注册税务/BAS 代理。以下数字按你录入的数据自动估算，仅供核对参考；正式申报 BAS 及可依赖的税务建议，请咨询注册税务/BAS 代理或核对 ATO。'
            : 'CIMO is a bookkeeping and calculation tool, not a registered tax or BAS agent. These figures are auto-estimated from your entries, for your review only. For lodging your BAS or advice you can rely on, consult a registered tax/BAS agent or the ATO.'}</p>
        </div>

        {/* Quarter selector */}
        <div className="bg-white dark:bg-[#2C2C2E] rounded-2xl border border-gray-200 dark:border-transparent p-5">
          <p className="text-sm font-medium text-gray-700 dark:text-[#F2F2F7] mb-3">{lang === 'zh' ? '选择季度' : 'Select Period'}</p>
          <div className="flex gap-2 mb-3">
            {[1, 2, 3, 4].map(q => (
              <button key={q} onClick={() => setSelectedQuarter(q)}
                className={`flex-1 py-2 rounded-xl text-sm font-medium transition ${selectedQuarter === q ? 'bg-blue-600 text-white' : 'bg-gray-100 dark:bg-[#3A3A3C] text-gray-600 dark:text-[#8E8E93]'}`}>
                Q{q}
              </button>
            ))}
          </div>
          <div className="flex gap-2">
            {years.map(y => (
              <button key={y} onClick={() => setSelectedYear(y)}
                className={`flex-1 py-2 rounded-xl text-sm font-medium transition ${selectedYear === y ? 'bg-blue-600 text-white' : 'bg-gray-100 dark:bg-[#3A3A3C] text-gray-600 dark:text-[#8E8E93]'}`}>
                {y}
              </button>
            ))}
          </div>
          <p className="text-xs text-[#8E8E93] mt-2 text-center">{quarterLabel}</p>
          <p className="text-xs mt-1 text-center font-medium" style={{ color: !mounted ? '#8E8E93' : dueDays < 0 ? '#FF453A' : dueDays <= 14 ? '#E3B341' : '#30D158' }}>{lang === 'zh' ? `BAS 申报截止 ${dueStr}` : `BAS due ${dueStr}`}{mounted ? (lang === 'zh' ? (dueDays >= 0 ? ` · 还剩 ${dueDays} 天` : ` · 已逾期 ${-dueDays} 天`) : (dueDays >= 0 ? ` · ${dueDays} days left` : ` · overdue ${-dueDays}d`)) : ''}</p>
        </div>

        {/* BAS Summary */}
        <div className="bg-white dark:bg-[#2C2C2E] rounded-2xl border border-gray-200 dark:border-transparent overflow-hidden">
          <div className="px-6 py-4 border-b border-gray-100 dark:border-[#3A3A3C]">
            <h2 className="font-semibold text-gray-900 dark:text-white">BAS Summary</h2>
            <p className="text-xs text-[#8E8E93] mt-0.5">{quarterLabel}</p>
          </div>

          <div className="divide-y divide-gray-100 dark:divide-[#3A3A3C]">
            <div className="px-6 py-3 flex justify-between">
              <div>
                <p className="text-sm font-medium text-gray-900 dark:text-[#F2F2F7]">G1 — Total Sales (inc. GST)</p>
                <p className="text-xs text-[#8E8E93]">{lang === 'zh' ? '含GST总销售额' : 'All invoiced amounts'}</p>
              </div>
              <p className="text-sm font-bold text-[#30D158]">${totalSales.toFixed(2)}</p>
            </div>
            <div className="px-6 py-3 flex justify-between bg-blue-50 dark:bg-[#0A84FF]/10">
              <div>
                <p className="text-sm font-semibold text-gray-900 dark:text-[#F2F2F7]">1A — GST on Sales</p>
                <p className="text-xs text-[#8E8E93]">G1 ÷ 11</p>
              </div>
              <p className="text-sm font-bold text-[#0A84FF]">${gstCollected.toFixed(2)}</p>
            </div>
            <div className="px-6 py-3 flex justify-between">
              <div>
                <p className="text-sm font-medium text-gray-900 dark:text-[#F2F2F7]">1B — GST on Purchases</p>
                <p className="text-xs text-[#8E8E93]">{lang === 'zh' ? '含税项÷11 + 不含税项×10%' : 'Incl. ÷11 + excl. ×10%'}</p>
              </div>
              <p className="text-sm font-bold text-[#FF453A]">${gstPaid.toFixed(2)}</p>
            </div>
          </div>

          <div className={`px-6 py-4 ${netGST >= 0 ? 'bg-red-50 dark:bg-[#FF453A]/10' : 'bg-green-50 dark:bg-[#30D158]/10'}`}>
            <div className="flex justify-between items-center">
              <div>
                <p className="font-bold text-gray-900 dark:text-white">Net GST {netGST >= 0 ? 'Payable' : 'Refundable'}</p>
                <p className="text-xs text-[#8E8E93]">1A − 1B</p>
              </div>
              <p className={`text-2xl font-bold ${netGST >= 0 ? 'text-[#FF453A]' : 'text-[#30D158]'}`}>${Math.abs(netGST).toFixed(2)}</p>
            </div>
          </div>

          <div className="px-6 py-3 border-t border-gray-100 dark:border-[#3A3A3C]">
            <p className="text-xs text-[#8E8E93] leading-relaxed">{lang === 'zh' ? 'Simpler BAS 格式 — 大多数澳洲小企业（GST 营业额 < $1000 万）只需申报 G1、1A、1B 三项。' : 'Simpler BAS format — most Australian small businesses (GST turnover < $10M) report only G1, 1A and 1B.'}</p>
          </div>
        </div>

        {/* Set aside for tax */}
        <div className="bg-white dark:bg-[#2C2C2E] rounded-2xl border border-gray-200 dark:border-transparent p-5">
          <p className="text-sm font-semibold text-gray-900 dark:text-white mb-1">{lang === 'zh' ? '建议预留税款' : 'Set aside for tax'}</p>
          <p className="text-xs text-[#8E8E93] mb-3">{lang === 'zh' ? '按本季数据估算，仅供参考' : 'Estimated from this quarter, indicative only'}</p>
          <div className="flex gap-2 mb-3">
            {[0, 25, 30, 37].map(pct => (
              <button key={pct} onClick={() => setTaxPct(pct)} className={`flex-1 py-2 rounded-xl text-sm font-medium transition ${taxPct === pct ? 'bg-blue-600 text-white' : 'bg-gray-100 dark:bg-[#3A3A3C] text-gray-600 dark:text-[#8E8E93]'}`}>{pct}%</button>
            ))}
          </div>
          <div className="space-y-2 text-sm">
            <div className="flex justify-between">
              <span className="text-[#8E8E93]">{lang === 'zh' ? '本季 GST 应缴' : 'GST payable (this Q)'}</span>
              <span className="font-medium text-gray-900 dark:text-[#F2F2F7]">${(netGST > 0 ? netGST : 0).toFixed(2)}</span>
            </div>
            <div className="flex justify-between">
              <span className="text-[#8E8E93]">{lang === 'zh' ? `所得税预留 (净利×${taxPct}%)` : `Income tax (profit ×${taxPct}%)`}</span>
              <span className="font-medium text-gray-900 dark:text-[#F2F2F7]">${(Math.max(salesExGST - costsExGST - totalLabor, 0) * taxPct / 100).toFixed(2)}</span>
            </div>
            <div className="flex justify-between border-t border-gray-100 dark:border-[#3A3A3C] pt-2 mt-2">
              <span className="font-semibold text-gray-900 dark:text-white">{lang === 'zh' ? '合计应预留' : 'Total to set aside'}</span>
              <span className="font-bold text-[#0A84FF]">${((netGST > 0 ? netGST : 0) + Math.max(salesExGST - costsExGST - totalLabor, 0) * taxPct / 100).toFixed(2)}</span>
            </div>
          </div>
        </div>

        {/* Breakdown */}
        <div className="bg-white dark:bg-[#2C2C2E] rounded-2xl border border-gray-200 dark:border-transparent p-5">
          <p className="text-sm font-semibold text-gray-900 dark:text-white mb-3">{lang === 'zh' ? '税前金额' : 'Ex-GST Breakdown'}</p>
          <div className="space-y-2 text-sm">
            <div className="flex justify-between">
              <span className="text-[#8E8E93]">{lang === 'zh' ? '销唭额 (税前)' : 'Sales (ex GST)'}</span>
              <span className="text-[#30D158] font-medium">${salesExGST.toFixed(2)}</span>
            </div>
            <div className="flex justify-between">
              <span className="text-[#8E8E93]">{lang === 'zh' ? '采购支出 (税前)' : 'Purchases (ex GST)'}</span>
              <span className="text-[#FF453A] font-medium">${costsExGST.toFixed(2)}</span>
            </div>
            <div className="flex justify-between">
              <span className="text-[#8E8E93]">{lang === 'zh' ? '人工成本' : 'Labour Cost'}</span>
              <span className="text-[#FF453A] font-medium">${totalLabor.toFixed(2)}</span>
            </div>
            <div className="flex justify-between border-t border-gray-100 dark:border-[#3A3A3C] pt-2 mt-2">
              <span className="font-semibold text-gray-900 dark:text-white">{lang === 'zh' ? '净利涖' : 'Net Profit'}</span>
              <span className={`font-bold ${(salesExGST - costsExGST - totalLabor) >= 0 ? 'text-[#30D158]' : 'text-[#FF453A]'}`}>
                ${(salesExGST - costsExGST - totalLabor).toFixed(2)}
              </span>
            </div>
          </div>
        </div>

        {/* Actions */}
        <div className="flex gap-3">
          <button onClick={copyToClipboard} className="flex-1 bg-gray-100 dark:bg-[#3A3A3C] text-gray-700 dark:text-[#F2F2F7] py-3 rounded-2xl text-sm font-semibold">
            {copied ? '✅ Copied!' : '📋 ' + (lang === 'zh' ? '复制报表' : 'Copy Report')}
          </button>
          <button onClick={() => window.print()} className="flex-1 bg-blue-600 text-white py-3 rounded-2xl text-sm font-semibold">
            🖨️ {lang === 'zh' ? '打印/PDF' : 'Print / PDF'}
          </button>
        </div>

        <p className="text-xs text-[#8E8E93] text-center pb-4">
          ⚠️ {lang === 'zh' ? '此报表仅供参考，请在提交BAS前咨询会计师' : 'For reference only. Consult your accountant before lodging BAS.'}
        </p>
      </main>
    </div>
  )
}
